version: '3.4'
services:
  web:
    command: ./bin/run-dev.sh
    env_file: .env
    volumes:
      - ./:/app:cached

  mariadb:
    volumes:
      - mysqlvolume:/var/lib/mysql

volumes:
    mysqlvolume:
